# Generated by Django 4.2.28 on 2026-02-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_basket',
            field=models.TextField(blank=True, default='', help_text='JSON snapshot of basket saved on logout.'),
        ),
    ]
