# Generated by Django 4.2.28 on 2026-02-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_nullable_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_reply',
            field=models.TextField(blank=True, help_text="Owner's public response to this review. Leave blank for no reply."),
        ),
        migrations.AddField(
            model_name='review',
            name='owner_reply_at',
            field=models.DateTimeField(blank=True, help_text='Automatically set when a reply is saved.', null=True),
        ),
    ]
