# Generated by Django 4.2.28 on 2026-02-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Displayed label e.g. 'Starter 1' or 'Main Course 2'.", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the deal form.')),
                ('categories', models.ManyToManyField(blank=True, help_text='Items from these categories are available to choose. Leave empty to allow all.', related_name='deal_slots', to='menu.category')),
                ('deal', models.ForeignKey(help_text='The deal MenuItem this selection slot belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='menu.menuitem')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
