# Generated by Django 4.2.28 on 2026-02-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.CharField(blank=True, help_text='Per-item special request (e.g. no onions)', max_length=300),
        ),
    ]
