# Generated by Django 4.2.28 on 2026-02-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_promocode_and_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Supports plain text. Keep it short.')),
                ('is_active', models.BooleanField(default=True, help_text='Only one announcement is shown at a time (the most recently created active one).')),
                ('style', models.CharField(choices=[('info', 'Info (blue)'), ('warning', 'Warning (yellow)'), ('danger', 'Danger (red)'), ('success', 'Success (green)')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Announcement',
                'verbose_name_plural': 'Site Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
