# Generated by Django 4.2.28 on 2026-02-26 12:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_site_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name, e.g. 'Weekend Deal'", max_length=100)),
                ('badge_text', models.CharField(blank=True, help_text="Short label shown to customers at checkout, e.g. '🎉 Happy Hour'. Defaults to name if blank.", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional public description shown at checkout.')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage off (%)'), ('fixed', 'Fixed amount off (£)')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 10 = 10%) or fixed amount in pounds (e.g. 2.50)', max_digits=6)),
                ('min_order', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum basket subtotal (£) required. Set to 0 for no minimum.', max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text='Leave blank to activate immediately.', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave blank for no expiry.', null=True)),
                ('uses_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Special Offer',
                'verbose_name_plural': 'Special Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
