# Generated by Django 4.2.28 on 2026-02-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_special_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='first_order_only',
            field=models.BooleanField(default=False, help_text='Restrict to new customers who have never placed an order.'),
        ),
    ]
